# .github/workflows/trading-bot.yml
name: Trading Bot - EMA Momentum Strategy

on:
  schedule:
    # Runs every 6 hours with 5-hour timezone adjustment
    - cron: '0 6,12,18,0 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  run-trading-strategy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run trading strategy
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
      run: |
        python main.py
        
    - name: Commit and push data files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv *.json *.txt *.pkl
        git diff --staged --quiet || git commit -m "Update trading data - $(date)"
        git push
